### ISSUE TITLE
`monopolygame` bin script is not available when installed from `npm`

### ISSUE THREAD

**Issue by JoeNyland** [MauriceConrad/Monopoly#2]
`npm i -g monopolygame` doesn't currently install the `monopolygame` executable, so users will get an error when they try to run the game from the CLI:

```
$ npm install -g monopolygame
+ monopolygame@0.1.0
added 1 package from 1 contributor in 1.71s
$ monopolygame
-bash: /Users/joenyland/.nvm/versions/node/v10.14.1/bin/monopolygame: No such file or directory
```

It looks like the version that's pushed to `npm` doesn't have this commit in it: https://github.com/MauriceConrad/Monopoly/commit/54eb7350fcb1db8d28757a40e2a0360b99e39184

I think maybe the latest version should be pushed to NPM 🙂

**Comment by ElyaConrad** [comment]
Oh, yes this is true...
I published it...

**Comment by ElyaConrad** [comment]
Sorry :D
